name: Build Container

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-containerize:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up rust
        uses: actions/setup_rust@v1
        with:
          rust-version: stable

      - name: Cache cargo deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build with cargo
        run: cargo build --release

      - name: Test with cargo
        run: cargo test --release
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build docker image
        run: docker build -t bit-casino-player-ms .

        
